kind: Deployment
apiVersion: apps/v1
metadata:
  name: kubernetes-demo
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: kubernetes-demo
   template:
      metadata:
        labels:
          app: kubernetes-demo
      spec:
       containers:
        - name: kubernetes-demo
          image: philic/kubernetes-demo
          imagePullPolicy: Always
          ports:
          - containerPort: 80