kind: Service                             
apiVersion: v1
metadata:
  name: kubernetes-demo
  labels:
    app: kubernetes-demo
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: kubernetes-demo                    
  type: LoadBalancer    